### PR TITLE
skyOS 2.8

### PR DESCRIPTION
**Pull request by PearComputer**
I essentially replaced some if statements with case-switch statements (this works in Python 3.10 and newer), re-added macOS support, and re-added AppleScript support.

### CODE REVIEW

**Comment by webbrowser11** [comment]
this would be 2.7, not planning to release this next update till the 30th or 31st but i will look at some of the changes you made and may accept a few of them. thank you for contributing!

**Comment by PearComputer** [comment]
Then maybe you could make it 2.7 then?

**Comment by webbrowser11** [comment]
yea i could change that

**Comment by webbrowser11** [comment]
i have one question...

**Comment by PearComputer** [comment]
What is that question?

**Comment by webbrowser11** [comment]
how do you install this on macs is python pre-installed on macs are there any other qequirments? we need to know to be able to make an install manual for SkyOS

**Comment by webbrowser11** [comment]
its tricky making software like this.

**Comment by webbrowser11** [comment]
SO MANY THINGS TO LEARN

**Comment by webbrowser11** [comment]
AND DO

**Comment by webbrowser11** [comment]
also did you give up on coffeOS i kinda liked it!

**Comment by webbrowser11** [comment]
oh also just mentioning this now you have to test everything and send us proof that it works before code changes can be merged now.

**Comment by PearComputer** [comment]
https://b098-185-177-126-134.ngrok-free.app/skyOS-demo.mov

**Comment by PearComputer** [comment]
https://b098-185-177-126-134.ngrok-free.app/skyOS-demo.mov

**Comment by PearComputer** [comment]
From what I have found, skyOS works fine with my changes, but the 2 setup checks were making it not work, so remove those and make "authenticated" be "True" instead of "False".

**Comment by webbrowser11** [comment]
i know i can call you wyatt now XD

**Comment by webbrowser11** [comment]
also you have to fix these yourself since you added them that's the policy the team agreed on. otherwise we cant merge. EEEEE do that and change readme.md to tell how to use and install on macs (especially extra dependencies that might be needed) show me that everything is working and we can merge thanks!

**Comment by webbrowser11** [comment]
(also sorry it took me so long to respond i was in the shower and eating dinner)

**Comment by webbrowser11** [comment]
btw, have you used that new browser "Tabiva" yet?

**Comment by webbrowser11** [comment]
also did you move accounts?

**Comment by PearComputer** [comment]
You know, you don't have to. That was just the name I set on my MacBook Air.

**Comment by PearComputer** [comment]
Not that I'm actually that name as I just looked up random boy's names and set that as my Mac's device name.

**Comment by webbrowser11** [comment]
okay

**Pull request closed without merging**
