### PR TITLE
Added support for macOS

### PR DESCRIPTION
**Pull request by G1aD05**
Added support for macOS and fixed some minor bugs.

### CODE REVIEW

**Comment by G1aD05** [comment]
Updated the source code

**Comment by webbrowser11** [comment]
make a release so i can test it.

**Comment by G1aD05** [comment]
> make a release so i can test it.

https://github.com/G1aD05/SkyOS-bugfix/releases/tag/bugfix

**Comment by webbrowser11** [comment]
maybe add how to run on MacOS into the readme now? (make another pull)

**Pull request merged**
