### PR TITLE
Made compatible with macOS

### PR DESCRIPTION
**Pull request by G1aD05**
There was no if statement for "Darwin", I also added an "Unsupported OS" message, and I fixed an issue with the "kernelState" variable, and I think that's it.

### CODE REVIEW

**Comment by webbrowser11** [comment]
ight ill see it later.

**Comment by webbrowser11** [comment]
source code NOT UP TO DATE and you did not log please do these things then open up a new pull request!

**Review by webbrowser11 — COMMENTED** [review]
sorry but that's a no for now.

**Comment by G1aD05** [comment]
> sorry but that's a no for now.

Sorry I forgot to update it

**Comment by webbrowser11** [comment]
its okay!

**Pull request closed without merging**
